// import Constant from '../lib/constant'
import _ from 'lodash'

//添加前缀
function addPrefix(arr,prefix) {
    var mirrored = {}
    prefix = prefix || "$RE_$"

    _.each(arr,(val) => {
      mirrored[val] = prefix + val
    }

    return mirrored
}

export default addPrefix([
  SET_PLATFORM,
  SET_VERSION,

  ACCESSTOKEN_GET_START,
  ACCESSTOKEN_GET_SUCCESS,
  ACCESSTOKEN_GET_FAILURE,

  USER_REGISTER_START,
  USER_REGISTER_SUCCESS,
  USER_REGISTER_FAILURE,

  USER_LOGIN_START,
  USER_LOGIN_SUCCESS,
  USER_LOGIN_FAILURE,

  LOGIN_MODULE_INIT,
  LOGIN_FORMFIELD_CHANGE

  DELETE_TOKEN_REQUEST,
  DELETE_TOKEN_SUCCESS,

  ON_LOGIN_STATE_CHANGE,

  ON_AUTH_FORM_FIELD_CHANGE,

  USER_LOGIN_START,
  USER_LOGIN_SUCCESS,
  USER_LOGIN_FAILURE,

  LOGOUT_REQUEST,
  LOGOUT_SUCCESS,
  LOGOUT_FAILURE,

  LOGGED_IN,
  LOGGED_OUT,

  SET_ACCESSTOKEN,

  RESET_PASSWORD_REQUEST,
  RESET_PASSWORD_SUCCESS,
  RESET_PASSWORD_FAILURE,

  GET_PROFILE_REQUEST,
  GET_PROFILE_SUCCESS,
  GET_PROFILE_FAILURE,

  ON_PROFILE_FORM_FIELD_CHANGE,
  REGISTER_FORMFIELD_CHANGE,
  REGISTER_MODULE_INIT,

  PROFILE_UPDATE_REQUEST,
  PROFILE_UPDATE_SUCCESS,
  PROFILE_UPDATE_FAILURE,

  SET_STATE,
  GET_STATE,
  SET_STORE

])
