import * as constantUtils from '../utils/constants'

const prefix = "SYS"

export default constantUtils.addPrefix([
  "SET_PLATFORM",
  "SET_VERSION",

  "ACCESSTOKEN_GET_START",
  "ACCESSTOKEN_GET_SUCCESS",
  "ACCESSTOKEN_GET_FAILURE",

  "DELETE_TOKEN_REQUEST",
  "DELETE_TOKEN_SUCCESS",

  "USER_REGISTER_START",
  "USER_REGISTER_SUCCESS",
  "USER_REGISTER_FAILURE",
  "USER_REGISTER_VIEW_INIT",
  "USER_REGISTER_FORMFIELD_CHANGE",

  "USER_LOGIN_START",
  "USER_LOGIN_SUCCESS",
  "USER_LOGIN_FAILURE",
  "USER_LOGIN_VIEW_INIT",
  "USER_LOGIN_FORMFIELD_CHANGE",

  "USER_LOGOUT_START",
  "USER_LOGOUT_SUCCESS",
  "USER_LOGOUT_FAILURE",
  "USER_LOGOUT_VIEW_INIT",
  "USER_LOGOUT_FORMFIELD_CHANGE",

  "USER_FORGOTPASSWORD_START",
  "USER_FORGOTPASSWORD_SUCCESS",
  "USER_FORGOTPASSWORD_FAILURE",
  "USER_FORGOTPASSWORD_VIEW_INIT",
  "USER_FORGOTPASSWORD_FORMFIELD_CHANGE",
  
  "LOGGED_IN",
  "LOGGED_OUT",

  "SET_ACCESSTOKEN",

  "USER_PROFILE_VIEW_INIT",
  "USER_PROFILE_FORMFIELD_CHANGE",

  "GET_STATE",
  "SET_STORE"

],prefix)
