const prefix = "RE_COMMON_"
import Constant from '../../lib/constant'

export default Constant.addPrefix({
  SET_PLATFORM: null,
  SET_VERSION: null,

  ACCESSTOKEN_REQUEST: null,
  ACCESSTOKEN_SUCCESS: null,
  ACCESSTOKEN_FAILURE: null,

  ON_LOGIN_STATE_CHANGE: null,

  USER_SIGNUP_REQUEST: null,
  USER_SIGNUP_SUCCESS: null,
  USER_SIGNUP_FAILURE: null,

  USER_LOGIN_REQUEST: null,
  USER_LOGIN_SUCCESS: null,
  USER_LOGIN_FAILURE: null,

  USER_LOGOUT_REQUEST: null,
  USER_LOGOUT_SUCCESS: null,
  USER_LOGOUT_FAILURE: null,

  LOGGED_IN: null,
  LOGGED_OUT: null,

  SET_ACCESSTOKEN: null,

  USER_RESETPASSWORD_REQUEST: null,
  USER_RESETPASSWORD_SUCCESS: null,
  USER_RESETPASSWORD_FAILURE: null,

  GET_PROFILE_REQUEST: null,
  GET_PROFILE_SUCCESS: null,
  GET_PROFILE_FAILURE: null,

  ON_PROFILE_FORM_FIELD_CHANGE: null,

  PROFILE_UPDATE_REQUEST: null,
  PROFILE_UPDATE_SUCCESS: null,
  PROFILE_UPDATE_FAILURE: null,

  SET_STATE: null,
  GET_STATE: null,
  SET_STORE: null
})
