const prefix = "RE_COMMON_"
import Constant from '../../lib/constant'

export default Constant.addPrefix({
  SET_PLATFORM: null,
  SET_VERSION: null,

  ACCESSTOKEN_REQUEST: null,
  ACCESSTOKEN_SUCCESS: null,
  ACCESSTOKEN_FAILURE: null,

  LOGGED_IN: null,
  LOGGED_OUT: null,

  SET_ACCESSTOKEN: null,

  ON_PROFILE_FORM_FIELD_CHANGE: null,

  SET_STORE: null,

  STATE_SET: null,
  STATE_GET: null,
  STATE_CHANGE: null,

  STATE_LOGOUT: null,
  STATE_REGISTER: null,
  STATE_LOGIN: null,
  STATE_FORGOT_PASSWORD: null,

  USER_SIGNUP_REQUEST: null,
  USER_SIGNUP_SUCCESS: null,
  USER_SIGNUP_FAILURE: null,

  USER_LOGIN_REQUEST: null,
  USER_LOGIN_SUCCESS: null,
  USER_LOGIN_FAILURE: null,

  USER_LOGOUT_REQUEST: null,
  USER_LOGOUT_SUCCESS: null,
  USER_LOGOUT_FAILURE: null,

  USER_RESETPASSWORD_REQUEST: null,
  USER_RESETPASSWORD_SUCCESS: null,
  USER_RESETPASSWORD_FAILURE: null,

  USER_GET_REQUEST: null,
  USER_GET_SUCCESS: null,
  USER_GET_FAILURE: null,

  USER_UPDATE_REQUEST: null,
  USER_UPDATE_SUCCESS: null,
  USER_UPDATE_FAILURE: null,
  ON_FORM_FIELD_CHANGE: null
  
})
