const prefix = "RE_COMMON_"
import Constant from '../../lib/constant'
export default Constant.addPrefix({
  USER_SIGNUP_REQUEST: null,
  USER_SIGNUP_SUCCESS: null,
  USER_SIGNUP_FAILURE: null,

  USER_LOGIN_REQUEST: null,
  USER_LOGIN_SUCCESS: null,
  USER_LOGIN_FAILURE: null,

  USER_LOGOUT_REQUEST: null,
  USER_LOGOUT_SUCCESS: null,
  USER_LOGOUT_FAILURE: null,

  USER_RESETPASSWORD_REQUEST: null,
  USER_RESETPASSWORD_SUCCESS: null,
  USER_RESETPASSWORD_FAILURE: null,

  USER_GET_REQUEST: null,
  USER_GET_SUCCESS: null,
  USER_GET_FAILURE: null,

  USER_UPDATE_REQUEST: null,
  USER_UPDATE_SUCCESS: null,
  USER_UPDATE_FAILURE: null,
})
