import * as constantUtils from '../../../utils/constants'

const prefix = "MODULE$USER"

export default constantUtils.addPrefix([

  "REGISTER_START",
  "REGISTER_SUCCESS",
  "REGISTER_FAILURE",
  "REGISTER_INIT_START",
  "REGISTER_FORMFIELD_CHANGE",

  "LOGIN_START",
  "LOGIN_SUCCESS",
  "LOGIN_FAILURE",
  "LOGIN_INIT_START",
  "LOGIN_FORMFIELD_CHANGE",

  "LOGOUT_START",
  "LOGOUT_SUCCESS",
  "LOGOUT_FAILURE",
  "LOGOUT_INIT_START",
  "LOGOUT_FORMFIELD_CHANGE",

  "FORGOTPASSWORD_START",
  "FORGOTPASSWORD_SUCCESS",
  "FORGOTPASSWORD_FAILURE",
  "FORGOTPASSWORD_INIT_START",
  "FORGOTPASSWORD_FORMFIELD_CHANGE",

  "PROFILE_GET_START",
  "PROFILE_GET_SUCCESS",
  "PROFILE_GET_FAILURE",

  "PROFILE_UPDATE_START",
  "PROFILE_UPDATE_SUCCESS",
  "PROFILE_UPDATE_FAILURE",

  "PROFILE_INIT_START",
  "PROFILE_FORMFIELD_CHANGE",

],prefix)
