import * as constantUtils from '../../../utils/constants'

const prefix = "RE$MODULE$"

export default constantUtils.addPrefix([

  "TODO_LIST",
  "TODO_LIST_INIT_START",

  "TODO_LIST_FIND_REQUEST_START",
  "TODO_LIST_FIND_REQUEST_SUCCESS",
  "TODO_LIST_FIND_REQUEST_FAILURE",

  "TODO_LIST_UPDATE_REQUEST_START",
  "TODO_LIST_UPDATE_REQUEST_SUCCESS",
  "TODO_LIST_UPDATE_REQUEST_FAILURE",

  "TODO_LIST_CREATE_REQUEST_START",
  "TODO_LIST_CREATE_REQUEST_SUCCESS",
  "TODO_LIST_CREATE_REQUEST_FAILURE",

  "TODO_LIST_GETCHANGESTREAM_REQUEST_START",
  "TODO_LIST_GETCHANGESTREAM_REQUEST_SUCCESS",
  "TODO_LIST_GETCHANGESTREAM_REQUEST_FAILURE",

  "TODO_LIST_CREATECHANGESTREAM_REQUEST_START",
  "TODO_LIST_CREATECHANGESTREAM_REQUEST_SUCCESS",
  "TODO_LIST_CREATECHANGESTREAM_REQUEST_FAILURE",

  "TODO_LIST_COUNT_REQUEST_START",
  "TODO_LIST_COUNT_REQUEST_SUCCESS",
  "TODO_LIST_COUNT_REQUEST_FAILURE",

  "TODO_LIST_UPSERT_REQUEST_START",
  "TODO_LIST_UPSERT_REQUEST_SUCCESS",
  "TODO_LIST_UPSERT_REQUEST_FAILURE",

  "TODO_ITEM",
  "TODO_ITEM_INIT_START",

  "TODO_ITEM_EXISTS_REQUEST_START",
  "TODO_ITEM_EXISTS_REQUEST_SUCCESS",
  "TODO_ITEM_EXISTS_REQUEST_FAILURE",

  "TODO_ITEM_FINDBYID_REQUEST_START",
  "TODO_ITEM_FINDBYID_REQUEST_SUCCESS",
  "TODO_ITEM_FINDBYID_REQUEST_FAILURE",

  "TODO_ITEM_FINDONE_REQUEST_START",
  "TODO_ITEM_FINDONE_REQUEST_SUCCESS",
  "TODO_ITEM_FINDONE_REQUEST_FAILURE",

  "TODO_ITEM_DELETE_REQUEST_START",
  "TODO_ITEM_DELETE_REQUEST_SUCCESS",
  "TODO_ITEM_DELETE_REQUEST_FAILURE",

  "TODO_ITEM_UPDATE_REQUEST_START",
  "TODO_ITEM_UPDATE_REQUEST_SUCCESS",
  "TODO_ITEM_UPDATE_REQUEST_FAILURE",

  "TODO_ITEM_UPDATEATTRIBUTES_REQUEST_START",
  "TODO_ITEM_UPDATEATTRIBUTES_REQUEST_SUCCESS",
  "TODO_ITEM_UPDATEATTRIBUTES_REQUEST_FAILURE",
],prefix)
